# Generated by Django 3.0.2 on 2020-02-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20200205_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='timeslot',
            field=models.IntegerField(choices=[(1, '10-11'), (2, '11-12'), (3, '12-01'), (4, '01-02'), (5, '02-03'), (6, '03-04'), (7, '04-05'), (8, '05-06'), (9, '06-07')], null=True),
        ),
    ]
