# Generated by Django 3.0.2 on 2020-02-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20200205_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='timeslot',
            field=models.IntegerField(null=True),
        ),
    ]
