# Generated by Django 3.0.2 on 2020-01-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_postmodel_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='title',
            field=models.CharField(default='New title', max_length=240),
            preserve_default=False,
        ),
    ]
