# Generated by Django 3.0.2 on 2020-01-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_postmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
