# Generated by Django 3.0.2 on 2020-01-23 08:07

import blog.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200123_0747'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='author_email',
            field=models.EmailField(blank=True, max_length=240, null=True, validators=[blog.validation.validate_the_author_email]),
        ),
    ]
