# Generated by Django 3.0.2 on 2020-02-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20200205_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cleanermodel',
            name='quality_score',
            field=models.FloatField(default=0),
        ),
    ]
