# Generated by Django 3.0.2 on 2020-02-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20200205_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=12, verbose_name='username'),
        ),
    ]
