# Generated by Django 3.0.2 on 2020-01-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(error_messages={'blank': 'This fields is not full,Please try again', 'unique': 'This Title is not unique, Please try again'}, max_length=200, unique=True),
        ),
    ]
